from .original import (
    SYSTEM_MESSAGE as SYSTEM_MESSAGE_DATA_ENTITY,
    USER_MESSAGE_TEMPLATE_DATA_ENTITY_RECOGNITION_2 as USER_MESSAGE_TEMPLATE_DATA_ENTITY,
    USER_MESSAGE_TEMPLATE_DATA_ENTITY_CLASSIFICATION,
    SYSTEM_MESSAGE_PURPOSE_ENTITY_RECOGNITION_SENTENCE as SYSTEM_MESSAGE_PURPOSE_ENTITY,
    USER_MESSAGE_TEMPLATE_PURPOSE_ENTITY_RECOGNITION_SENTENCE as USER_MESSAGE_TEMPLATE_PURPOSE_ENTITY,
    USER_MESSAGE_TEMPLATE_PURPOSE_CATEGORY_CLASSIFICATION_SENTENCE as USER_MESSAGE_TEMPLATE_PURPOSE_CATEGORY,
    SYSTEM_MESSAGE_ACTION_RECOGNITION_SENTENCE as SYSTEM_MESSAGE_ACTION_RECOGNITION,
    USER_MESSAGE_TEMPLATE_ACTION_RECOGNITION_SENTENCE as USER_MESSAGE_TEMPLATE_ACTION_RECOGNITION,
    SYSTEM_MESSAGE_RELATION_RECOGNITION,
    USER_MESSAGE_TEMPLATE_RELATION_RECOGNITION,
)

from .preprocess import (
    SYSTEM_MESSAGE_DATA_ENTITY_CLASSIFICATION,
    SYSTEM_MESSAGE_PURPOSE_CATEGORY_CLASSIFICATION,
)
