WEBSITES_BY_CONFLICTS__50 = {
    0: ["amazonaws.com", "googleusercontent.com", "mozilla.org"],
    1: [
        "google.com",
        "googleapis.com",
        "youtube.com",
        "gstatic.com",
        "googlevideo.com",
        "googletagmanager.com",
        "doubleclick.net",
        "wordpress.org",
        "youtu.be",
        "github.com",
        "digicert.com",
        "goo.gl",
        "bit.ly",
        "gandi.net",
        "google-analytics.com",
        "reddit.com",
    ],
    2: ["yahoo.com"],
    3: ["azure.com", "tiktok.com"],
    4: ["office.net"],
    5: ["fastly.net", "netflix.com", "adobe.com"],
    6: [
        "linkedin.com",
        "amazon.com",
        "bing.com",
        "wikipedia.org",
        "pinterest.com",
        "spotify.com",
        "vimeo.com",
    ],
    7: ["icloud.com", "intuit.com"],
    8: ["zoom.us"],
    9: ["facebook.com", "cloudflare.com", "instagram.com"],
    10: ["apple.com"],
    12: ["wordpress.com"],
    13: [
        "office.com",
        "live.com",
        "microsoftonline.com",
        "sharepoint.com",
        "skype.com",
        "windows.net",
        "msn.com",
        "office365.com",
        "roblox.com",
    ],
}


PERSONAS_BY_CONFLICTS__50 = {
    0: [
        "comm-internal-1st-allow",
        "comm-internal-1st-no",
        "contact-ad-no",
        "picture-pubsec-no",
        "social-sns-allow",
        "social-sns-no",
        "identifying-pubsec-no",
    ],
    1: ["contact-analytics-no", "location-ad-3rd-no", "location-ad-no"],
    9: ["picture-pubsec-allow"],
    10: ["health-research-allow"],
    16: [
        "contact-ad-allow",
        "contact-analytics-1st-allow",
        "contact-analytics-all-allow",
        "location-analytics-no",
    ],
    20: ["contact-1st-only"],
    22: ["data-ad-3rd-no"],
    25: ["location-analytics-all-allow"],
    26: [
        "location-analytics-1st-allow",
        "location-internal-1st-allow",
        "location-ad-allow",
    ],
    42: ["location-3rd-no"],
}


WEBSITES_AND_CONFLICT_SEGMENTS_BY_CONFLICTS__50 = {
    0: {"amazonaws.com": {}, "googleusercontent.com": {}, "mozilla.org": {}},
    1: {
        "bit.ly": {"data-ad-3rd-no": 8},
        "digicert.com": {"data-ad-3rd-no": 5},
        "doubleclick.net": {"location-3rd-no": 1},
        "gandi.net": {"location-3rd-no": 3},
        "github.com": {"health-research-allow": 1},
        "goo.gl": {"location-3rd-no": 1},
        "google-analytics.com": {"location-3rd-no": 1},
        "google.com": {"location-3rd-no": 1},
        "googleapis.com": {"location-3rd-no": 1},
        "googletagmanager.com": {"location-3rd-no": 1},
        "googlevideo.com": {"location-3rd-no": 1},
        "gstatic.com": {"location-3rd-no": 1},
        "reddit.com": {"location-3rd-no": 1},
        "wordpress.org": {"data-ad-3rd-no": 2},
        "youtu.be": {"location-3rd-no": 1},
        "youtube.com": {"location-3rd-no": 1},
    },
    2: {"yahoo.com": {"data-ad-3rd-no": 3, "location-3rd-no": 1}},
    3: {
        "azure.com": {
            "contact-1st-only": 1,
            "health-research-allow": 1,
            "location-3rd-no": 1,
        },
        "tiktok.com": {
            "contact-1st-only": 3,
            "data-ad-3rd-no": 5,
            "location-3rd-no": 1,
        },
    },
    4: {
        "office.net": {
            "contact-1st-only": 1,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
        }
    },
    5: {
        "adobe.com": {
            "location-3rd-no": 2,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "fastly.net": {
            "contact-1st-only": 2,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
            "location-3rd-no": 1,
        },
        "netflix.com": {
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
    },
    6: {
        "amazon.com": {
            "data-ad-3rd-no": 2,
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "bing.com": {
            "data-ad-3rd-no": 8,
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "linkedin.com": {
            "contact-1st-only": 1,
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "pinterest.com": {
            "data-ad-3rd-no": 6,
            "location-3rd-no": 2,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 2,
        },
        "spotify.com": {
            "data-ad-3rd-no": 7,
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "vimeo.com": {
            "data-ad-3rd-no": 10,
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "wikipedia.org": {
            "location-3rd-no": 5,
            "location-ad-allow": 3,
            "location-analytics-1st-allow": 5,
            "location-analytics-all-allow": 2,
            "location-analytics-no": 5,
            "location-internal-1st-allow": 5,
        },
    },
    7: {
        "icloud.com": {
            "contact-1st-only": 1,
            "location-3rd-no": 4,
            "location-ad-allow": 4,
            "location-analytics-1st-allow": 4,
            "location-analytics-all-allow": 4,
            "location-analytics-no": 4,
            "location-internal-1st-allow": 4,
        },
        "intuit.com": {
            "data-ad-3rd-no": 8,
            "location-3rd-no": 2,
            "location-ad-allow": 2,
            "location-analytics-1st-allow": 2,
            "location-analytics-all-allow": 2,
            "location-analytics-no": 2,
            "location-internal-1st-allow": 2,
        },
    },
    8: {
        "zoom.us": {
            "data-ad-3rd-no": 17,
            "location-3rd-no": 4,
            "location-ad-allow": 3,
            "location-analytics-1st-allow": 4,
            "location-analytics-all-allow": 2,
            "location-analytics-no": 4,
            "location-internal-1st-allow": 4,
            "picture-pubsec-allow": 1,
        }
    },
    9: {
        "cloudflare.com": {
            "contact-1st-only": 1,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "facebook.com": {
            "contact-1st-only": 1,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
            "location-3rd-no": 2,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 2,
        },
        "instagram.com": {
            "contact-1st-only": 1,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-no": 1,
            "location-internal-1st-allow": 1,
        },
    },
    10: {
        "apple.com": {
            "contact-1st-only": 1,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
            "location-3rd-no": 4,
            "location-ad-allow": 4,
            "location-analytics-1st-allow": 4,
            "location-analytics-all-allow": 4,
            "location-analytics-no": 4,
            "location-internal-1st-allow": 4,
        }
    },
    12: {
        "wordpress.com": {
            "contact-1st-only": 2,
            "contact-ad-allow": 2,
            "contact-analytics-1st-allow": 2,
            "contact-analytics-all-allow": 2,
            "contact-analytics-no": 2,
            "data-ad-3rd-no": 6,
            "location-3rd-no": 3,
            "location-ad-allow": 3,
            "location-analytics-1st-allow": 3,
            "location-analytics-all-allow": 2,
            "location-analytics-no": 3,
            "location-internal-1st-allow": 3,
        }
    },
    13: {
        "live.com": {
            "contact-1st-only": 6,
            "contact-ad-allow": 4,
            "contact-analytics-1st-allow": 4,
            "contact-analytics-all-allow": 4,
            "data-ad-3rd-no": 38,
            "health-research-allow": 9,
            "location-3rd-no": 9,
            "location-ad-allow": 9,
            "location-analytics-1st-allow": 9,
            "location-analytics-all-allow": 9,
            "location-analytics-no": 9,
            "location-internal-1st-allow": 9,
            "picture-pubsec-allow": 5,
        },
        "microsoftonline.com": {
            "contact-1st-only": 7,
            "contact-ad-allow": 4,
            "contact-analytics-1st-allow": 4,
            "contact-analytics-all-allow": 4,
            "data-ad-3rd-no": 34,
            "health-research-allow": 2,
            "location-3rd-no": 12,
            "location-ad-allow": 12,
            "location-analytics-1st-allow": 12,
            "location-analytics-all-allow": 12,
            "location-analytics-no": 12,
            "location-internal-1st-allow": 12,
            "picture-pubsec-allow": 1,
        },
        "msn.com": {
            "contact-1st-only": 6,
            "contact-ad-allow": 4,
            "contact-analytics-1st-allow": 4,
            "contact-analytics-all-allow": 4,
            "data-ad-3rd-no": 38,
            "health-research-allow": 9,
            "location-3rd-no": 9,
            "location-ad-allow": 9,
            "location-analytics-1st-allow": 9,
            "location-analytics-all-allow": 9,
            "location-analytics-no": 9,
            "location-internal-1st-allow": 9,
            "picture-pubsec-allow": 5,
        },
        "office.com": {
            "contact-1st-only": 6,
            "contact-ad-allow": 4,
            "contact-analytics-1st-allow": 4,
            "contact-analytics-all-allow": 4,
            "data-ad-3rd-no": 38,
            "health-research-allow": 9,
            "location-3rd-no": 9,
            "location-ad-allow": 9,
            "location-analytics-1st-allow": 9,
            "location-analytics-all-allow": 9,
            "location-analytics-no": 9,
            "location-internal-1st-allow": 9,
            "picture-pubsec-allow": 5,
        },
        "office365.com": {
            "contact-1st-only": 6,
            "contact-ad-allow": 4,
            "contact-analytics-1st-allow": 4,
            "contact-analytics-all-allow": 4,
            "data-ad-3rd-no": 38,
            "health-research-allow": 9,
            "location-3rd-no": 9,
            "location-ad-allow": 9,
            "location-analytics-1st-allow": 9,
            "location-analytics-all-allow": 9,
            "location-analytics-no": 9,
            "location-internal-1st-allow": 9,
            "picture-pubsec-allow": 5,
        },
        "roblox.com": {
            "contact-1st-only": 3,
            "contact-ad-allow": 3,
            "contact-analytics-1st-allow": 3,
            "contact-analytics-all-allow": 3,
            "data-ad-3rd-no": 4,
            "location-3rd-no": 3,
            "location-ad-3rd-no": 3,
            "location-ad-allow": 3,
            "location-ad-no": 3,
            "location-analytics-1st-allow": 3,
            "location-analytics-all-allow": 3,
            "location-analytics-no": 3,
            "location-internal-1st-allow": 3,
        },
        "sharepoint.com": {
            "contact-1st-only": 6,
            "contact-ad-allow": 4,
            "contact-analytics-1st-allow": 4,
            "contact-analytics-all-allow": 4,
            "data-ad-3rd-no": 38,
            "health-research-allow": 9,
            "location-3rd-no": 9,
            "location-ad-allow": 9,
            "location-analytics-1st-allow": 9,
            "location-analytics-all-allow": 9,
            "location-analytics-no": 9,
            "location-internal-1st-allow": 9,
            "picture-pubsec-allow": 5,
        },
        "skype.com": {
            "contact-1st-only": 6,
            "contact-ad-allow": 4,
            "contact-analytics-1st-allow": 4,
            "contact-analytics-all-allow": 4,
            "data-ad-3rd-no": 38,
            "health-research-allow": 9,
            "location-3rd-no": 9,
            "location-ad-allow": 9,
            "location-analytics-1st-allow": 9,
            "location-analytics-all-allow": 9,
            "location-analytics-no": 9,
            "location-internal-1st-allow": 9,
            "picture-pubsec-allow": 5,
        },
        "windows.net": {
            "contact-1st-only": 7,
            "contact-ad-allow": 5,
            "contact-analytics-1st-allow": 5,
            "contact-analytics-all-allow": 5,
            "data-ad-3rd-no": 37,
            "health-research-allow": 1,
            "location-3rd-no": 11,
            "location-ad-allow": 11,
            "location-analytics-1st-allow": 11,
            "location-analytics-all-allow": 11,
            "location-analytics-no": 11,
            "location-internal-1st-allow": 11,
            "picture-pubsec-allow": 5,
        },
    },
}


PERSONA_AND_CONFLICG_SEGMENTS_BY_CONFLICTS__50 = {
    0: {
        "comm-internal-1st-allow": {},
        "comm-internal-1st-no": {},
        "contact-ad-no": {},
        "identifying-pubsec-no": {},
        "picture-pubsec-no": {},
        "social-sns-allow": {},
        "social-sns-no": {},
    },
    1: {
        "contact-analytics-no": {"wordpress.com": 2},
        "location-ad-3rd-no": {"roblox.com": 3},
        "location-ad-no": {"roblox.com": 3},
    },
    9: {
        "picture-pubsec-allow": {
            "live.com": 5,
            "microsoftonline.com": 1,
            "msn.com": 5,
            "office.com": 5,
            "office365.com": 5,
            "sharepoint.com": 5,
            "skype.com": 5,
            "windows.net": 5,
            "zoom.us": 1,
        }
    },
    10: {
        "health-research-allow": {
            "azure.com": 1,
            "github.com": 1,
            "live.com": 9,
            "microsoftonline.com": 2,
            "msn.com": 9,
            "office.com": 9,
            "office365.com": 9,
            "sharepoint.com": 9,
            "skype.com": 9,
            "windows.net": 1,
        }
    },
    16: {
        "contact-ad-allow": {
            "apple.com": 1,
            "cloudflare.com": 1,
            "facebook.com": 1,
            "fastly.net": 1,
            "instagram.com": 1,
            "live.com": 4,
            "microsoftonline.com": 4,
            "msn.com": 4,
            "office.com": 4,
            "office.net": 1,
            "office365.com": 4,
            "roblox.com": 3,
            "sharepoint.com": 4,
            "skype.com": 4,
            "windows.net": 5,
            "wordpress.com": 2,
        },
        "contact-analytics-1st-allow": {
            "apple.com": 1,
            "cloudflare.com": 1,
            "facebook.com": 1,
            "fastly.net": 1,
            "instagram.com": 1,
            "live.com": 4,
            "microsoftonline.com": 4,
            "msn.com": 4,
            "office.com": 4,
            "office.net": 1,
            "office365.com": 4,
            "roblox.com": 3,
            "sharepoint.com": 4,
            "skype.com": 4,
            "windows.net": 5,
            "wordpress.com": 2,
        },
        "contact-analytics-all-allow": {
            "apple.com": 1,
            "cloudflare.com": 1,
            "facebook.com": 1,
            "fastly.net": 1,
            "instagram.com": 1,
            "live.com": 4,
            "microsoftonline.com": 4,
            "msn.com": 4,
            "office.com": 4,
            "office.net": 1,
            "office365.com": 4,
            "roblox.com": 3,
            "sharepoint.com": 4,
            "skype.com": 4,
            "windows.net": 5,
            "wordpress.com": 2,
        },
        "location-analytics-no": {
            "apple.com": 4,
            "icloud.com": 4,
            "instagram.com": 1,
            "intuit.com": 2,
            "live.com": 9,
            "microsoftonline.com": 12,
            "msn.com": 9,
            "office.com": 9,
            "office365.com": 9,
            "roblox.com": 3,
            "sharepoint.com": 9,
            "skype.com": 9,
            "wikipedia.org": 5,
            "windows.net": 11,
            "wordpress.com": 3,
            "zoom.us": 4,
        },
    },
    20: {
        "contact-1st-only": {
            "apple.com": 1,
            "azure.com": 1,
            "cloudflare.com": 1,
            "facebook.com": 1,
            "fastly.net": 2,
            "icloud.com": 1,
            "instagram.com": 1,
            "linkedin.com": 1,
            "live.com": 6,
            "microsoftonline.com": 7,
            "msn.com": 6,
            "office.com": 6,
            "office.net": 1,
            "office365.com": 6,
            "roblox.com": 3,
            "sharepoint.com": 6,
            "skype.com": 6,
            "tiktok.com": 3,
            "windows.net": 7,
            "wordpress.com": 2,
        }
    },
    22: {
        "data-ad-3rd-no": {
            "amazon.com": 2,
            "bing.com": 8,
            "bit.ly": 8,
            "digicert.com": 5,
            "intuit.com": 8,
            "live.com": 38,
            "microsoftonline.com": 34,
            "msn.com": 38,
            "office.com": 38,
            "office365.com": 38,
            "pinterest.com": 6,
            "roblox.com": 4,
            "sharepoint.com": 38,
            "skype.com": 38,
            "spotify.com": 7,
            "tiktok.com": 5,
            "vimeo.com": 10,
            "windows.net": 37,
            "wordpress.com": 6,
            "wordpress.org": 2,
            "yahoo.com": 3,
            "zoom.us": 17,
        }
    },
    25: {
        "location-analytics-all-allow": {
            "adobe.com": 1,
            "amazon.com": 1,
            "apple.com": 4,
            "bing.com": 1,
            "cloudflare.com": 1,
            "facebook.com": 1,
            "icloud.com": 4,
            "intuit.com": 2,
            "linkedin.com": 1,
            "live.com": 9,
            "microsoftonline.com": 12,
            "msn.com": 9,
            "netflix.com": 1,
            "office.com": 9,
            "office365.com": 9,
            "pinterest.com": 1,
            "roblox.com": 3,
            "sharepoint.com": 9,
            "skype.com": 9,
            "spotify.com": 1,
            "vimeo.com": 1,
            "wikipedia.org": 2,
            "windows.net": 11,
            "wordpress.com": 2,
            "zoom.us": 2,
        }
    },
    26: {
        "location-ad-allow": {
            "adobe.com": 1,
            "amazon.com": 1,
            "apple.com": 4,
            "bing.com": 1,
            "cloudflare.com": 1,
            "facebook.com": 1,
            "icloud.com": 4,
            "instagram.com": 1,
            "intuit.com": 2,
            "linkedin.com": 1,
            "live.com": 9,
            "microsoftonline.com": 12,
            "msn.com": 9,
            "netflix.com": 1,
            "office.com": 9,
            "office365.com": 9,
            "pinterest.com": 1,
            "roblox.com": 3,
            "sharepoint.com": 9,
            "skype.com": 9,
            "spotify.com": 1,
            "vimeo.com": 1,
            "wikipedia.org": 3,
            "windows.net": 11,
            "wordpress.com": 3,
            "zoom.us": 3,
        },
        "location-analytics-1st-allow": {
            "adobe.com": 1,
            "amazon.com": 1,
            "apple.com": 4,
            "bing.com": 1,
            "cloudflare.com": 1,
            "facebook.com": 1,
            "icloud.com": 4,
            "instagram.com": 1,
            "intuit.com": 2,
            "linkedin.com": 1,
            "live.com": 9,
            "microsoftonline.com": 12,
            "msn.com": 9,
            "netflix.com": 1,
            "office.com": 9,
            "office365.com": 9,
            "pinterest.com": 1,
            "roblox.com": 3,
            "sharepoint.com": 9,
            "skype.com": 9,
            "spotify.com": 1,
            "vimeo.com": 1,
            "wikipedia.org": 5,
            "windows.net": 11,
            "wordpress.com": 3,
            "zoom.us": 4,
        },
        "location-internal-1st-allow": {
            "adobe.com": 1,
            "amazon.com": 1,
            "apple.com": 4,
            "bing.com": 1,
            "cloudflare.com": 1,
            "facebook.com": 2,
            "icloud.com": 4,
            "instagram.com": 1,
            "intuit.com": 2,
            "linkedin.com": 1,
            "live.com": 9,
            "microsoftonline.com": 12,
            "msn.com": 9,
            "netflix.com": 1,
            "office.com": 9,
            "office365.com": 9,
            "pinterest.com": 2,
            "roblox.com": 3,
            "sharepoint.com": 9,
            "skype.com": 9,
            "spotify.com": 1,
            "vimeo.com": 1,
            "wikipedia.org": 5,
            "windows.net": 11,
            "wordpress.com": 3,
            "zoom.us": 4,
        },
    },
    42: {
        "location-3rd-no": {
            "adobe.com": 2,
            "amazon.com": 1,
            "apple.com": 4,
            "azure.com": 1,
            "bing.com": 1,
            "cloudflare.com": 1,
            "doubleclick.net": 1,
            "facebook.com": 2,
            "fastly.net": 1,
            "gandi.net": 3,
            "goo.gl": 1,
            "google-analytics.com": 1,
            "google.com": 1,
            "googleapis.com": 1,
            "googletagmanager.com": 1,
            "googlevideo.com": 1,
            "gstatic.com": 1,
            "icloud.com": 4,
            "instagram.com": 1,
            "intuit.com": 2,
            "linkedin.com": 1,
            "live.com": 9,
            "microsoftonline.com": 12,
            "msn.com": 9,
            "netflix.com": 1,
            "office.com": 9,
            "office365.com": 9,
            "pinterest.com": 2,
            "reddit.com": 1,
            "roblox.com": 3,
            "sharepoint.com": 9,
            "skype.com": 9,
            "spotify.com": 1,
            "tiktok.com": 1,
            "vimeo.com": 1,
            "wikipedia.org": 5,
            "windows.net": 11,
            "wordpress.com": 3,
            "yahoo.com": 1,
            "youtu.be": 1,
            "youtube.com": 1,
            "zoom.us": 4,
        }
    },
}


WEBSITES_WITH_SAME_POLICY = [
    ["googleapis.com", "google-analytics.com"],
    ["gstatic.com", "doubleclick.net"],
    [
        "office.com",
        "live.com",
        "sharepoint.com",
        "skype.com",
        "msn.com",
        "office365.com",
    ],
    ["googletagmanager.com", "youtu.be"],
]
