WEBSITES_BY_CONFLICTS = {
    0: [
        "amazonaws.com",
        "googleusercontent.com",
        "mozilla.org",
        "opera.com",
        "europa.eu",
        "nist.gov",
        "apache.org",
        "casalemedia.com",
        "w3.org",
        "ebay.com",
        "salesforce.com",
        "twitch.tv",
        "mit.edu",
        "scorecardresearch.com",
        "ubuntu.com",
    ],
    1: [
        "google.com",
        "googleapis.com",
        "youtube.com",
        "gstatic.com",
        "googlevideo.com",
        "googletagmanager.com",
        "wordpress.org",
        "github.com",
        "digicert.com",
        "goo.gl",
        "bit.ly",
        "gandi.net",
        "reddit.com",
        "snapchat.com",
        "comcast.net",
        "nih.gov",
        "x.com",
        "medium.com",
        "soundcloud.com",
        "tds.net",
        "taboola.com",
        "rubiconproject.com",
        "doubleverify.com",
        "creativecommons.org",
        "nginx.com",
        "sciencedirect.com",
        "ring.com",
    ],
    2: [
        "yahoo.com",
        "samsung.com",
        "ui.com",
        "sentry.io",
        "applovin.com",
        "android.com",
        "shopify.com",
        "researchgate.net",
    ],
    3: ["azure.com", "tiktok.com", "sourceforge.net"],
    4: ["office.net", "epicgames.com", "smartadserver.com"],
    5: [
        "fastly.net",
        "netflix.com",
        "adobe.com",
        "dropbox.com",
        "nytimes.com",
        "flickr.com",
        "paypal.com",
        "bbc.co.uk",
        "bbc.com",
        "b-cdn.net",
    ],
    6: [
        "linkedin.com",
        "amazon.com",
        "bing.com",
        "wikipedia.org",
        "pinterest.com",
        "spotify.com",
        "vimeo.com",
        "unity3d.com",
        "webex.com",
        "cnn.com",
        "theguardian.com",
        "slack.com",
        "imdb.com",
    ],
    7: ["icloud.com", "intuit.com", "forbes.com"],
    8: ["zoom.us", "criteo.com"],
    9: [
        "facebook.com",
        "cloudflare.com",
        "instagram.com",
        "tumblr.com",
        "kaspersky.com",
    ],
    10: ["apple.com", "xiaomi.com", "t.co"],
    11: ["registrar-servers.com"],
    12: ["wordpress.com", "t-mobile.com"],
    13: [
        "office.com",
        "microsoftonline.com",
        "windows.net",
        "roblox.com",
        "windows.com",
    ],
}


PERSONAS_BY_CONFLICTS = {
    0: [
        "comm-internal-1st-allow",
        "comm-internal-1st-no",
        "contact-ad-no",
        "picture-pubsec-no",
        "social-sns-allow",
        "social-sns-no",
        "identifying-pubsec-no",
    ],
    3: [
        "contact-analytics-no",
        "location-ad-3rd-no",
        "location-ad-no",
    ],
    6: [
        "health-research-allow",
        "picture-pubsec-allow",
    ],
    17: ["location-analytics-no"],
    20: ["contact-analytics-all-allow"],
    21: [
        "contact-ad-allow",
        "contact-analytics-1st-allow",
    ],
    31: ["contact-1st-only"],
    37: ["data-ad-3rd-no"],
    40: ["location-analytics-all-allow"],
    42: [
        "location-analytics-1st-allow",
        "location-internal-1st-allow",
        "location-ad-allow",
    ],
    70: ["location-3rd-no"],
}


WEBSITES_AND_CONFLICT_SEGMENTS_BY_CONFLICTS = {
    0: {
        "amazonaws.com": {},
        "apache.org": {},
        "casalemedia.com": {},
        "ebay.com": {},
        "europa.eu": {},
        "googleusercontent.com": {},
        "mit.edu": {},
        "mozilla.org": {},
        "nist.gov": {},
        "opera.com": {},
        "salesforce.com": {},
        "scorecardresearch.com": {},
        "twitch.tv": {},
        "ubuntu.com": {},
        "w3.org": {},
    },
    1: {
        "bit.ly": {"data-ad-3rd-no": 8},
        "comcast.net": {"data-ad-3rd-no": 8},
        "creativecommons.org": {"location-3rd-no": 2},
        "digicert.com": {"data-ad-3rd-no": 5},
        "doubleverify.com": {"data-ad-3rd-no": 7},
        "gandi.net": {"location-3rd-no": 3},
        "github.com": {"health-research-allow": 1},
        "goo.gl": {"location-3rd-no": 1},
        "google.com": {"location-3rd-no": 1},
        "googleapis.com": {"location-3rd-no": 1},
        "googletagmanager.com": {"location-3rd-no": 1},
        "googlevideo.com": {"location-3rd-no": 1},
        "gstatic.com": {"location-3rd-no": 1},
        "medium.com": {"location-3rd-no": 1},
        "nginx.com": {"data-ad-3rd-no": 5},
        "nih.gov": {"picture-pubsec-allow": 1},
        "reddit.com": {"location-3rd-no": 1},
        "ring.com": {"location-3rd-no": 1},
        "rubiconproject.com": {"data-ad-3rd-no": 2},
        "sciencedirect.com": {"contact-1st-only": 1},
        "snapchat.com": {"location-3rd-no": 1},
        "soundcloud.com": {"location-3rd-no": 1},
        "taboola.com": {"location-3rd-no": 1},
        "tds.net": {"location-3rd-no": 1},
        "wordpress.org": {"data-ad-3rd-no": 2},
        "x.com": {"contact-1st-only": 1},
        "youtube.com": {"location-3rd-no": 1},
    },
    2: {
        "android.com": {
            "data-ad-3rd-no": 4,
            "location-3rd-no": 1,
        },
        "applovin.com": {
            "data-ad-3rd-no": 7,
            "location-3rd-no": 1,
        },
        "researchgate.net": {
            "data-ad-3rd-no": 14,
            "location-3rd-no": 1,
        },
        "samsung.com": {
            "data-ad-3rd-no": 7,
            "location-3rd-no": 1,
        },
        "sentry.io": {
            "contact-1st-only": 1,
            "data-ad-3rd-no": 20,
        },
        "shopify.com": {
            "data-ad-3rd-no": 23,
            "location-3rd-no": 3,
        },
        "ui.com": {
            "data-ad-3rd-no": 8,
            "location-3rd-no": 1,
        },
        "yahoo.com": {
            "data-ad-3rd-no": 3,
            "location-3rd-no": 1,
        },
    },
    3: {
        "azure.com": {
            "contact-1st-only": 1,
            "health-research-allow": 1,
            "location-3rd-no": 1,
        },
        "sourceforge.net": {
            "contact-1st-only": 1,
            "data-ad-3rd-no": 5,
            "location-3rd-no": 1,
        },
        "tiktok.com": {
            "contact-1st-only": 3,
            "data-ad-3rd-no": 5,
            "location-3rd-no": 1,
        },
    },
    4: {
        "epicgames.com": {
            "contact-1st-only": 1,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
        },
        "office.net": {
            "contact-1st-only": 1,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
        },
        "smartadserver.com": {
            "contact-1st-only": 1,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
        },
    },
    5: {
        "adobe.com": {
            "location-3rd-no": 2,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "b-cdn.net": {
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "bbc.co.uk": {
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "bbc.com": {
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "dropbox.com": {
            "location-3rd-no": 2,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 2,
            "location-analytics-no": 2,
            "location-internal-1st-allow": 2,
        },
        "fastly.net": {
            "contact-1st-only": 2,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
            "location-3rd-no": 1,
        },
        "flickr.com": {
            "location-3rd-no": 4,
            "location-ad-allow": 2,
            "location-analytics-1st-allow": 2,
            "location-analytics-all-allow": 2,
            "location-internal-1st-allow": 4,
        },
        "netflix.com": {
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "nytimes.com": {
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "paypal.com": {
            "location-3rd-no": 3,
            "location-ad-allow": 2,
            "location-analytics-1st-allow": 2,
            "location-analytics-all-allow": 2,
            "location-internal-1st-allow": 3,
        },
    },
    6: {
        "amazon.com": {
            "data-ad-3rd-no": 2,
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "bing.com": {
            "data-ad-3rd-no": 8,
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "cnn.com": {
            "data-ad-3rd-no": 8,
            "location-3rd-no": 2,
            "location-ad-allow": 2,
            "location-analytics-1st-allow": 2,
            "location-analytics-all-allow": 2,
            "location-internal-1st-allow": 2,
        },
        "imdb.com": {
            "data-ad-3rd-no": 4,
            "location-3rd-no": 2,
            "location-ad-allow": 2,
            "location-analytics-1st-allow": 2,
            "location-analytics-all-allow": 2,
            "location-internal-1st-allow": 2,
        },
        "linkedin.com": {
            "contact-1st-only": 1,
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "pinterest.com": {
            "data-ad-3rd-no": 6,
            "location-3rd-no": 2,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 2,
        },
        "slack.com": {
            "contact-1st-only": 1,
            "location-3rd-no": 2,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "spotify.com": {
            "data-ad-3rd-no": 7,
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "theguardian.com": {
            "data-ad-3rd-no": 8,
            "location-3rd-no": 3,
            "location-ad-allow": 3,
            "location-analytics-1st-allow": 3,
            "location-analytics-all-allow": 3,
            "location-internal-1st-allow": 3,
        },
        "unity3d.com": {
            "contact-1st-only": 1,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-no": 1,
            "data-ad-3rd-no": 19,
            "location-3rd-no": 3,
        },
        "vimeo.com": {
            "data-ad-3rd-no": 10,
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "webex.com": {
            "data-ad-3rd-no": 7,
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "wikipedia.org": {
            "location-3rd-no": 5,
            "location-ad-allow": 3,
            "location-analytics-1st-allow": 5,
            "location-analytics-all-allow": 2,
            "location-analytics-no": 5,
            "location-internal-1st-allow": 5,
        },
    },
    7: {
        "forbes.com": {
            "contact-1st-only": 1,
            "data-ad-3rd-no": 12,
            "location-3rd-no": 2,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 2,
        },
        "icloud.com": {
            "contact-1st-only": 1,
            "location-3rd-no": 4,
            "location-ad-allow": 4,
            "location-analytics-1st-allow": 4,
            "location-analytics-all-allow": 4,
            "location-analytics-no": 4,
            "location-internal-1st-allow": 4,
        },
        "intuit.com": {
            "data-ad-3rd-no": 8,
            "location-3rd-no": 2,
            "location-ad-allow": 2,
            "location-analytics-1st-allow": 2,
            "location-analytics-all-allow": 2,
            "location-analytics-no": 2,
            "location-internal-1st-allow": 2,
        },
    },
    8: {
        "criteo.com": {
            "location-3rd-no": 2,
            "location-ad-3rd-no": 2,
            "location-ad-allow": 2,
            "location-ad-no": 2,
            "location-analytics-1st-allow": 2,
            "location-analytics-all-allow": 1,
            "location-analytics-no": 2,
            "location-internal-1st-allow": 2,
        },
        "zoom.us": {
            "data-ad-3rd-no": 17,
            "location-3rd-no": 4,
            "location-ad-allow": 3,
            "location-analytics-1st-allow": 4,
            "location-analytics-all-allow": 2,
            "location-analytics-no": 4,
            "location-internal-1st-allow": 4,
            "picture-pubsec-allow": 1,
        },
    },
    9: {
        "cloudflare.com": {
            "contact-1st-only": 1,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "facebook.com": {
            "contact-1st-only": 1,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
            "location-3rd-no": 2,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 2,
        },
        "instagram.com": {
            "contact-1st-only": 1,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-no": 1,
            "location-internal-1st-allow": 1,
        },
        "kaspersky.com": {
            "contact-1st-only": 1,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
            "location-3rd-no": 1,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 1,
        },
        "tumblr.com": {
            "contact-1st-only": 1,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
            "location-3rd-no": 2,
            "location-ad-allow": 1,
            "location-analytics-1st-allow": 1,
            "location-analytics-all-allow": 1,
            "location-internal-1st-allow": 2,
        },
    },
    10: {
        "apple.com": {
            "contact-1st-only": 1,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
            "location-3rd-no": 4,
            "location-ad-allow": 4,
            "location-analytics-1st-allow": 4,
            "location-analytics-all-allow": 4,
            "location-analytics-no": 4,
            "location-internal-1st-allow": 4,
        },
        "t.co": {
            "contact-1st-only": 5,
            "contact-ad-allow": 4,
            "contact-analytics-1st-allow": 4,
            "contact-analytics-all-allow": 4,
            "data-ad-3rd-no": 3,
            "location-3rd-no": 3,
            "location-ad-allow": 2,
            "location-analytics-1st-allow": 2,
            "location-analytics-all-allow": 2,
            "location-internal-1st-allow": 3,
        },
        "xiaomi.com": {
            "contact-1st-only": 2,
            "contact-ad-allow": 2,
            "contact-analytics-1st-allow": 2,
            "contact-analytics-all-allow": 2,
            "location-3rd-no": 5,
            "location-ad-allow": 5,
            "location-analytics-1st-allow": 5,
            "location-analytics-all-allow": 5,
            "location-analytics-no": 5,
            "location-internal-1st-allow": 5,
        },
    },
    11: {
        "registrar-servers.com": {
            "contact-1st-only": 3,
            "contact-ad-allow": 2,
            "contact-analytics-1st-allow": 3,
            "contact-analytics-all-allow": 2,
            "contact-analytics-no": 3,
            "location-3rd-no": 3,
            "location-ad-allow": 2,
            "location-analytics-1st-allow": 3,
            "location-analytics-all-allow": 2,
            "location-analytics-no": 3,
            "location-internal-1st-allow": 3,
        }
    },
    12: {
        "t-mobile.com": {
            "contact-1st-only": 2,
            "contact-ad-allow": 1,
            "contact-analytics-1st-allow": 1,
            "contact-analytics-all-allow": 1,
            "location-3rd-no": 7,
            "location-ad-3rd-no": 7,
            "location-ad-allow": 7,
            "location-ad-no": 7,
            "location-analytics-1st-allow": 7,
            "location-analytics-all-allow": 7,
            "location-analytics-no": 7,
            "location-internal-1st-allow": 7,
        },
        "wordpress.com": {
            "contact-1st-only": 2,
            "contact-ad-allow": 2,
            "contact-analytics-1st-allow": 2,
            "contact-analytics-all-allow": 2,
            "contact-analytics-no": 2,
            "data-ad-3rd-no": 6,
            "location-3rd-no": 3,
            "location-ad-allow": 3,
            "location-analytics-1st-allow": 3,
            "location-analytics-all-allow": 2,
            "location-analytics-no": 3,
            "location-internal-1st-allow": 3,
        },
    },
    13: {
        "microsoftonline.com": {
            "contact-1st-only": 7,
            "contact-ad-allow": 4,
            "contact-analytics-1st-allow": 4,
            "contact-analytics-all-allow": 4,
            "data-ad-3rd-no": 34,
            "health-research-allow": 2,
            "location-3rd-no": 12,
            "location-ad-allow": 12,
            "location-analytics-1st-allow": 12,
            "location-analytics-all-allow": 12,
            "location-analytics-no": 12,
            "location-internal-1st-allow": 12,
            "picture-pubsec-allow": 1,
        },
        "office.com": {
            "contact-1st-only": 6,
            "contact-ad-allow": 4,
            "contact-analytics-1st-allow": 4,
            "contact-analytics-all-allow": 4,
            "data-ad-3rd-no": 38,
            "health-research-allow": 9,
            "location-3rd-no": 9,
            "location-ad-allow": 9,
            "location-analytics-1st-allow": 9,
            "location-analytics-all-allow": 9,
            "location-analytics-no": 9,
            "location-internal-1st-allow": 9,
            "picture-pubsec-allow": 5,
        },
        "roblox.com": {
            "contact-1st-only": 3,
            "contact-ad-allow": 3,
            "contact-analytics-1st-allow": 3,
            "contact-analytics-all-allow": 3,
            "data-ad-3rd-no": 4,
            "location-3rd-no": 3,
            "location-ad-3rd-no": 3,
            "location-ad-allow": 3,
            "location-ad-no": 3,
            "location-analytics-1st-allow": 3,
            "location-analytics-all-allow": 3,
            "location-analytics-no": 3,
            "location-internal-1st-allow": 3,
        },
        "windows.com": {
            "contact-1st-only": 7,
            "contact-ad-allow": 5,
            "contact-analytics-1st-allow": 5,
            "contact-analytics-all-allow": 5,
            "data-ad-3rd-no": 40,
            "health-research-allow": 8,
            "location-3rd-no": 12,
            "location-ad-allow": 12,
            "location-analytics-1st-allow": 12,
            "location-analytics-all-allow": 12,
            "location-analytics-no": 12,
            "location-internal-1st-allow": 12,
            "picture-pubsec-allow": 4,
        },
        "windows.net": {
            "contact-1st-only": 7,
            "contact-ad-allow": 5,
            "contact-analytics-1st-allow": 5,
            "contact-analytics-all-allow": 5,
            "data-ad-3rd-no": 37,
            "health-research-allow": 1,
            "location-3rd-no": 11,
            "location-ad-allow": 11,
            "location-analytics-1st-allow": 11,
            "location-analytics-all-allow": 11,
            "location-analytics-no": 11,
            "location-internal-1st-allow": 11,
            "picture-pubsec-allow": 5,
        },
    },
}


PERSONA_AND_CONFLICG_SEGMENTS_BY_CONFLICTS = {
    0: {
        "comm-internal-1st-allow": {},
        "comm-internal-1st-no": {},
        "contact-ad-no": {},
        "identifying-pubsec-no": {},
        "picture-pubsec-no": {},
        "social-sns-allow": {},
        "social-sns-no": {},
    },
    3: {
        "contact-analytics-no": {
            "registrar-servers.com": 3,
            "unity3d.com": 1,
            "wordpress.com": 2,
        },
        "location-ad-3rd-no": {
            "criteo.com": 2,
            "roblox.com": 3,
            "t-mobile.com": 7,
        },
        "location-ad-no": {
            "criteo.com": 2,
            "roblox.com": 3,
            "t-mobile.com": 7,
        },
    },
    6: {
        "health-research-allow": {
            "azure.com": 1,
            "github.com": 1,
            "microsoftonline.com": 2,
            "office.com": 9,
            "windows.com": 8,
            "windows.net": 1,
        },
        "picture-pubsec-allow": {
            "microsoftonline.com": 1,
            "nih.gov": 1,
            "office.com": 5,
            "windows.com": 4,
            "windows.net": 5,
            "zoom.us": 1,
        },
    },
    17: {
        "location-analytics-no": {
            "apple.com": 4,
            "criteo.com": 2,
            "dropbox.com": 2,
            "icloud.com": 4,
            "instagram.com": 1,
            "intuit.com": 2,
            "microsoftonline.com": 12,
            "office.com": 9,
            "registrar-servers.com": 3,
            "roblox.com": 3,
            "t-mobile.com": 7,
            "wikipedia.org": 5,
            "windows.com": 12,
            "windows.net": 11,
            "wordpress.com": 3,
            "xiaomi.com": 5,
            "zoom.us": 4,
        }
    },
    20: {
        "contact-analytics-all-allow": {
            "apple.com": 1,
            "cloudflare.com": 1,
            "epicgames.com": 1,
            "facebook.com": 1,
            "fastly.net": 1,
            "instagram.com": 1,
            "kaspersky.com": 1,
            "microsoftonline.com": 4,
            "office.com": 4,
            "office.net": 1,
            "registrar-servers.com": 2,
            "roblox.com": 3,
            "smartadserver.com": 1,
            "t-mobile.com": 1,
            "t.co": 4,
            "tumblr.com": 1,
            "windows.com": 5,
            "windows.net": 5,
            "wordpress.com": 2,
            "xiaomi.com": 2,
        }
    },
    21: {
        "contact-ad-allow": {
            "apple.com": 1,
            "cloudflare.com": 1,
            "epicgames.com": 1,
            "facebook.com": 1,
            "fastly.net": 1,
            "instagram.com": 1,
            "kaspersky.com": 1,
            "microsoftonline.com": 4,
            "office.com": 4,
            "office.net": 1,
            "registrar-servers.com": 2,
            "roblox.com": 3,
            "smartadserver.com": 1,
            "t-mobile.com": 1,
            "t.co": 4,
            "tumblr.com": 1,
            "unity3d.com": 1,
            "windows.com": 5,
            "windows.net": 5,
            "wordpress.com": 2,
            "xiaomi.com": 2,
        },
        "contact-analytics-1st-allow": {
            "apple.com": 1,
            "cloudflare.com": 1,
            "epicgames.com": 1,
            "facebook.com": 1,
            "fastly.net": 1,
            "instagram.com": 1,
            "kaspersky.com": 1,
            "microsoftonline.com": 4,
            "office.com": 4,
            "office.net": 1,
            "registrar-servers.com": 3,
            "roblox.com": 3,
            "smartadserver.com": 1,
            "t-mobile.com": 1,
            "t.co": 4,
            "tumblr.com": 1,
            "unity3d.com": 1,
            "windows.com": 5,
            "windows.net": 5,
            "wordpress.com": 2,
            "xiaomi.com": 2,
        },
    },
    31: {
        "contact-1st-only": {
            "apple.com": 1,
            "azure.com": 1,
            "cloudflare.com": 1,
            "epicgames.com": 1,
            "facebook.com": 1,
            "fastly.net": 2,
            "forbes.com": 1,
            "icloud.com": 1,
            "instagram.com": 1,
            "kaspersky.com": 1,
            "linkedin.com": 1,
            "microsoftonline.com": 7,
            "office.com": 6,
            "office.net": 1,
            "registrar-servers.com": 3,
            "roblox.com": 3,
            "sciencedirect.com": 1,
            "sentry.io": 1,
            "slack.com": 1,
            "smartadserver.com": 1,
            "sourceforge.net": 1,
            "t-mobile.com": 2,
            "t.co": 5,
            "tiktok.com": 3,
            "tumblr.com": 1,
            "unity3d.com": 1,
            "windows.com": 7,
            "windows.net": 7,
            "wordpress.com": 2,
            "x.com": 1,
            "xiaomi.com": 2,
        }
    },
    37: {
        "data-ad-3rd-no": {
            "amazon.com": 2,
            "android.com": 4,
            "applovin.com": 7,
            "bing.com": 8,
            "bit.ly": 8,
            "cnn.com": 8,
            "comcast.net": 8,
            "digicert.com": 5,
            "doubleverify.com": 7,
            "forbes.com": 12,
            "imdb.com": 4,
            "intuit.com": 8,
            "microsoftonline.com": 34,
            "nginx.com": 5,
            "office.com": 38,
            "pinterest.com": 6,
            "researchgate.net": 14,
            "roblox.com": 4,
            "rubiconproject.com": 2,
            "samsung.com": 7,
            "sentry.io": 20,
            "shopify.com": 23,
            "sourceforge.net": 5,
            "spotify.com": 7,
            "t.co": 3,
            "theguardian.com": 8,
            "tiktok.com": 5,
            "ui.com": 8,
            "unity3d.com": 19,
            "vimeo.com": 10,
            "webex.com": 7,
            "windows.com": 40,
            "windows.net": 37,
            "wordpress.com": 6,
            "wordpress.org": 2,
            "yahoo.com": 3,
            "zoom.us": 17,
        }
    },
    40: {
        "location-analytics-all-allow": {
            "adobe.com": 1,
            "amazon.com": 1,
            "apple.com": 4,
            "b-cdn.net": 1,
            "bbc.co.uk": 1,
            "bbc.com": 1,
            "bing.com": 1,
            "cloudflare.com": 1,
            "cnn.com": 2,
            "criteo.com": 1,
            "facebook.com": 1,
            "flickr.com": 2,
            "forbes.com": 1,
            "icloud.com": 4,
            "imdb.com": 2,
            "intuit.com": 2,
            "kaspersky.com": 1,
            "linkedin.com": 1,
            "microsoftonline.com": 12,
            "netflix.com": 1,
            "nytimes.com": 1,
            "office.com": 9,
            "paypal.com": 2,
            "pinterest.com": 1,
            "registrar-servers.com": 2,
            "roblox.com": 3,
            "slack.com": 1,
            "spotify.com": 1,
            "t-mobile.com": 7,
            "t.co": 2,
            "theguardian.com": 3,
            "tumblr.com": 1,
            "vimeo.com": 1,
            "webex.com": 1,
            "wikipedia.org": 2,
            "windows.com": 12,
            "windows.net": 11,
            "wordpress.com": 2,
            "xiaomi.com": 5,
            "zoom.us": 2,
        }
    },
    42: {
        "location-ad-allow": {
            "adobe.com": 1,
            "amazon.com": 1,
            "apple.com": 4,
            "b-cdn.net": 1,
            "bbc.co.uk": 1,
            "bbc.com": 1,
            "bing.com": 1,
            "cloudflare.com": 1,
            "cnn.com": 2,
            "criteo.com": 2,
            "dropbox.com": 1,
            "facebook.com": 1,
            "flickr.com": 2,
            "forbes.com": 1,
            "icloud.com": 4,
            "imdb.com": 2,
            "instagram.com": 1,
            "intuit.com": 2,
            "kaspersky.com": 1,
            "linkedin.com": 1,
            "microsoftonline.com": 12,
            "netflix.com": 1,
            "nytimes.com": 1,
            "office.com": 9,
            "paypal.com": 2,
            "pinterest.com": 1,
            "registrar-servers.com": 2,
            "roblox.com": 3,
            "slack.com": 1,
            "spotify.com": 1,
            "t-mobile.com": 7,
            "t.co": 2,
            "theguardian.com": 3,
            "tumblr.com": 1,
            "vimeo.com": 1,
            "webex.com": 1,
            "wikipedia.org": 3,
            "windows.com": 12,
            "windows.net": 11,
            "wordpress.com": 3,
            "xiaomi.com": 5,
            "zoom.us": 3,
        },
        "location-analytics-1st-allow": {
            "adobe.com": 1,
            "amazon.com": 1,
            "apple.com": 4,
            "b-cdn.net": 1,
            "bbc.co.uk": 1,
            "bbc.com": 1,
            "bing.com": 1,
            "cloudflare.com": 1,
            "cnn.com": 2,
            "criteo.com": 2,
            "dropbox.com": 2,
            "facebook.com": 1,
            "flickr.com": 2,
            "forbes.com": 1,
            "icloud.com": 4,
            "imdb.com": 2,
            "instagram.com": 1,
            "intuit.com": 2,
            "kaspersky.com": 1,
            "linkedin.com": 1,
            "microsoftonline.com": 12,
            "netflix.com": 1,
            "nytimes.com": 1,
            "office.com": 9,
            "paypal.com": 2,
            "pinterest.com": 1,
            "registrar-servers.com": 3,
            "roblox.com": 3,
            "slack.com": 1,
            "spotify.com": 1,
            "t-mobile.com": 7,
            "t.co": 2,
            "theguardian.com": 3,
            "tumblr.com": 1,
            "vimeo.com": 1,
            "webex.com": 1,
            "wikipedia.org": 5,
            "windows.com": 12,
            "windows.net": 11,
            "wordpress.com": 3,
            "xiaomi.com": 5,
            "zoom.us": 4,
        },
        "location-internal-1st-allow": {
            "adobe.com": 1,
            "amazon.com": 1,
            "apple.com": 4,
            "b-cdn.net": 1,
            "bbc.co.uk": 1,
            "bbc.com": 1,
            "bing.com": 1,
            "cloudflare.com": 1,
            "cnn.com": 2,
            "criteo.com": 2,
            "dropbox.com": 2,
            "facebook.com": 2,
            "flickr.com": 4,
            "forbes.com": 2,
            "icloud.com": 4,
            "imdb.com": 2,
            "instagram.com": 1,
            "intuit.com": 2,
            "kaspersky.com": 1,
            "linkedin.com": 1,
            "microsoftonline.com": 12,
            "netflix.com": 1,
            "nytimes.com": 1,
            "office.com": 9,
            "paypal.com": 3,
            "pinterest.com": 2,
            "registrar-servers.com": 3,
            "roblox.com": 3,
            "slack.com": 1,
            "spotify.com": 1,
            "t-mobile.com": 7,
            "t.co": 3,
            "theguardian.com": 3,
            "tumblr.com": 2,
            "vimeo.com": 1,
            "webex.com": 1,
            "wikipedia.org": 5,
            "windows.com": 12,
            "windows.net": 11,
            "wordpress.com": 3,
            "xiaomi.com": 5,
            "zoom.us": 4,
        },
    },
    70: {
        "location-3rd-no": {
            "adobe.com": 2,
            "amazon.com": 1,
            "android.com": 1,
            "apple.com": 4,
            "applovin.com": 1,
            "azure.com": 1,
            "b-cdn.net": 1,
            "bbc.co.uk": 1,
            "bbc.com": 1,
            "bing.com": 1,
            "cloudflare.com": 1,
            "cnn.com": 2,
            "creativecommons.org": 2,
            "criteo.com": 2,
            "dropbox.com": 2,
            "facebook.com": 2,
            "fastly.net": 1,
            "flickr.com": 4,
            "forbes.com": 2,
            "gandi.net": 3,
            "goo.gl": 1,
            "google.com": 1,
            "googleapis.com": 1,
            "googletagmanager.com": 1,
            "googlevideo.com": 1,
            "gstatic.com": 1,
            "icloud.com": 4,
            "imdb.com": 2,
            "instagram.com": 1,
            "intuit.com": 2,
            "kaspersky.com": 1,
            "linkedin.com": 1,
            "medium.com": 1,
            "microsoftonline.com": 12,
            "netflix.com": 1,
            "nytimes.com": 1,
            "office.com": 9,
            "paypal.com": 3,
            "pinterest.com": 2,
            "reddit.com": 1,
            "registrar-servers.com": 3,
            "researchgate.net": 1,
            "ring.com": 1,
            "roblox.com": 3,
            "samsung.com": 1,
            "shopify.com": 3,
            "slack.com": 2,
            "snapchat.com": 1,
            "soundcloud.com": 1,
            "sourceforge.net": 1,
            "spotify.com": 1,
            "t-mobile.com": 7,
            "t.co": 3,
            "taboola.com": 1,
            "tds.net": 1,
            "theguardian.com": 3,
            "tiktok.com": 1,
            "tumblr.com": 2,
            "ui.com": 1,
            "unity3d.com": 3,
            "vimeo.com": 1,
            "webex.com": 1,
            "wikipedia.org": 5,
            "windows.com": 12,
            "windows.net": 11,
            "wordpress.com": 3,
            "xiaomi.com": 5,
            "yahoo.com": 1,
            "youtube.com": 1,
            "zoom.us": 4,
        }
    },
}


AVERAGE_CONFLICT_RATE_0 = {
    0: 0.0,
    1: 0.013069619562015904,
    2: 0.021345442493733515,
    3: 0.037098637098637095,
    4: 0.04831335524404831,
    5: 0.08669917305164582,
    6: 0.06824379410355953,
    7: 0.08414681548114832,
    8: 0.08021390374331551,
    9: 0.0848005042095442,
    10: 0.0753807210641743,
    11: 0.2619047619047619,
    12: 0.06755819087869804,
    13: 0.02870030506050795,
}


AVERAGE_CONFLICT_RATE_1 = {
    0: 0.0,
    1: 0.7639329805996473,
    2: 0.24096459096459097,
    3: 0.5873015873015873,
    4: 1.0,
    5: 0.7996031746031746,
    6: 0.5023773996349247,
    7: 0.32666666666666666,
    8: 0.36923076923076925,
    9: 0.9272727272727274,
    10: 0.31093358395989973,
    11: 0.3793103448275862,
    12: 0.28017883755588674,
    13: 0.14393578935784088,
}


AVERAGE_CONFLICT_RATE_2 = {
    0: 0.0,
    1: 0.7639329805996473,
    2: 0.24096459096459097,
    3: 0.6444444444444445,
    4: 4.0,
    5: 3.4583333333333335,
    6: 1.0821881017533193,
    7: 0.9833333333333334,
    8: 2.1818181818181817,
    9: 3.9,
    10: 1.6125541125541127,
    11: 3.6666666666666665,
    12: 1.2666666666666666,
    13: 0.4277432872050116,
}


AVERAGE_CONFLICT_RATE_3 = {
    0: 0.0,
    1: 0.06205961492779553,
    2: 0.0757395252187289,
    3: 0.1288888888888889,
    4: 0.18305021813793743,
    5: 0.3823321948321948,
    6: 0.22791724946538722,
    7: 0.2664102564102564,
    8: 0.5100182149362477,
    9: 0.29556650246305416,
    10: 0.21436703096539164,
    11: 0.9166666666666666,
    12: 0.23565652676164806,
    13: 0.09591636471701777,
}


AVERAGE_CONFLICT_RATE_4 = {
    0: 0.0,
    1: 0.06205961492779553,
    2: 0.0766094041274195,
    3: 0.1288888888888889,
    4: 0.18305021813793743,
    5: 0.3866611991611991,
    6: 0.22791724946538722,
    7: 0.2664102564102564,
    8: 0.5100182149362477,
    9: 0.29556650246305416,
    10: 0.23218599033816423,
    11: 0.9166666666666666,
    12: 0.23565652676164806,
    13: 0.09632915540595756,
}
